apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{ include "frontend.release_labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      {{ include "frontend.release_labels" . | indent 6 }}
      deployment: frontend
  template:
    metadata:
      labels:
        {{ include "frontend.release_labels" . | indent 8 }}
        deployment: frontend
        silta-ingress: allow
      annotations:
        # We use a checksum to redeploy the pods when the configMap changes.
        configMap-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      enableServiceLinks: false
      containers:
      # Nginx container
      - name: nginx
        image: {{ .Values.nginx.image | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf # mount nginx-conf configmap volume to /etc/nginx
          readOnly: true
          subPath: nginx_conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/frontend.conf # mount nginx-conf configmap volume to /etc/nginx
          readOnly: true
          subPath: frontend_conf
        {{- if .Values.nginx.extraConfig }}
        - name: config
          # provide empty configuration file in /etc/nginx/conf.d for users to populate
          mountPath: /etc/nginx/conf.d/misc.conf
          readOnly: true
          subPath: extraConfig
        {{- end }}
        {{- if .Values.nginx.basicauth.enabled }}
        - name: nginx-basicauth
          mountPath: /etc/nginx/.htaccess
          readOnly: true
          subPath: .htaccess
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
        resources:
          {{ .Values.nginx.resources | toYaml | nindent 10 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
            items:
              - key: nginx_conf
                path: nginx_conf
              - key: frontend_conf
                path: frontend_conf
        {{- if .Values.nginx.basicauth.enabled }}
        - name: nginx-basicauth
          secret:
            secretName: {{ .Release.Name }}-secrets-frontend
            items:
              - key: .htaccess
                path: .htaccess
        {{- end }}
---
{{- if .Values.nginx.autoscaling.enabled }}
apiVersion: {{ include "frontend.autoscaling.api-version" . | trim }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{- include "frontend.release_labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-nginx
  minReplicas: {{ .Values.nginx.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nginx.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.nginx.autoscaling.metrics | nindent 4 }}
{{- end }}
